### ISSUE TITLE
Ability to provide thumbnail

### ISSUE THREAD

**Issue by maxnoe** [matplotlib/matplotblog#5]
I wanted to contribute a Post, but the plot does look really bad with the auto created thumbnail (very wide aspect ratio).

How could I explicitly provide a thumbnail for the list view that is not auto-generated from `featuredImage` or prevent that the `featuredImage` is show at the top of the post?

**Comment by davidevaleriani** [comment]
You can now hide the featuredImage from the top of the post by adding a parameter `showOnTop` and set it to `false`. For example:

```
resources:
- name: featuredImage
  src: image.jpg
  params:
    showOnTop: false
```
