### ISSUE TITLE
Lack of featured image in blog post

### ISSUE THREAD

**Issue by dkajtoch** [matplotlib/matplotblog#8]
I am finishing my blog post and wanted to add summary figure at the top and in post "card-body" with the following code:
```
resources:
- name: featuredImage
  src: "fig4.jpg"
  params:
    description: "My description
    showOnTop: true
```
The imaged indeed appears at the top of the blog post, but it is not visible as in the snippet below. Any fix to that? Or maybe there is some ratio limit?
![image](https://user-images.githubusercontent.com/32985207/70155041-d5c98e00-16b1-11ea-8e50-b93f01adf32c.png)
